---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gnomad-browser
  labels:
    component: gnomad-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gnomad-browser
  template:
    metadata:
      labels:
        name: gnomad-browser
    spec:
      containers:
        - name: web
          image: gnomad-browser
          env:
            - name: API_URL
              value: http://$(GRAPHQL_API_SERVICE)
            - name: INGRESS_IP
              valueFrom:
                configMapKeyRef:
                  name: ingress-ip
                  key: ip
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'
            limits:
              cpu: '250m'
              memory: '512Mi'
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
      nodeSelector:
        cloud.google.com/gke-nodepool: 'default-pool'
