---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gnomad-graphql-api
  labels:
    component: gnomad-graphql-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gnomad-graphql-api
  template:
    metadata:
      labels:
        name: gnomad-graphql-api
    spec:
      containers:
        - name: app
          image: gnomad-graphql-api
          env:
            - name: PORT
              value: '8000'
            - name: INTERNAL_API_URL
              value: http://$(INTERNAL_API_SERVICE)
            - name: CACHE_REDIS_URL
              value: redis://redis:6379/1
            - name: RATE_LIMITER_REDIS_URL
              value: redis://redis:6379/2
            - name: TRUST_PROXY
              value: '3'
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: '500m'
              memory: '1Gi'
            limits:
              cpu: '1'
              memory: '2Gi'
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
      initContainers:
        - name: wait-for-internal-api
          image: busybox
          command:
            - sh
            - -c
            - "until wget -q http://$(INTERNAL_API_SERVICE)/health/ready; do sleep 2; done"
      nodeSelector:
        cloud.google.com/gke-nodepool: 'default-pool'
