apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./browser.deployment.yaml
  - ./graphql-api.deployment.yaml
  - ./graphql-api.service.yaml
  - ./internal-api.deployment.yaml
  - ./internal-api.service.yaml
images:
  - name: busybox
    newName: mirror.gcr.io/library/busybox
vars:
  - name: GRAPHQL_API_SERVICE
    objref:
      kind: Service
      name: gnomad-graphql-api
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: INTERNAL_API_SERVICE
    objref:
      kind: Service
      name: gnomad-internal-api
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
