apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data-temp
  labels:
    component: es-data-temp
spec:
  serviceName: elasticsearch-temp
  replicas: 5
  template:
    metadata:
      labels:
        component: es-data-temp
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-data-temp
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: gcr.io/exac-gnomad/docker-elasticsearch-kubernetes:5.5.1 
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms26g -Xmx26g"
        - name: "SHARD_ALLOCATION_AWARENESS_ATTR"
          value: "/etc/hostname"
        - name: "SHARD_ALLOCATION_AWARENESS"
          value: "data_node_hostname"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      nodeSelector:
        cloud.google.com/gke-nodepool: "elastic-temp"
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: ''
      selector:
        matchLabels:
          role: es-temp-disk
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1000G
